# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greenpoint',
            name='canopy',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='greenpoint',
            name='height',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='greenpoint',
            name='stem',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='greenpoint',
            name='type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
