# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-29 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='greenpoint',
            name='city',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
