# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_auto_20170807_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greenpoint',
            name='user',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
