# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-09 02:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_auto_20170807_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('badge_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('max_points', models.IntegerField()),
                ('min_points', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('city', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('green_index', models.IntegerField(default=0)),
                ('population_density', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('username', models.CharField(blank=True, max_length=60)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=60)),
                ('activation_key', models.CharField(blank=True, max_length=40)),
                ('photo_loaded', models.BooleanField(default=False)),
                ('country', models.CharField(max_length=120)),
                ('city', models.CharField(max_length=120)),
                ('game_points', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='greenpoint',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.UserProfile'),
        ),
    ]
