# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 14:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_userprofile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greenpoint',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='API.UserProfile'),
        ),
    ]
