# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 14:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_auto_20170809_1022'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='greenpoint',
            unique_together=set([('latitud', 'longitud')]),
        ),
    ]
