# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_auto_20170809_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greenpoint',
            name='canopy',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='greenpoint',
            name='height',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='greenpoint',
            name='stem',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
