# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 15:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0009_auto_20170809_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greenpoint',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='API.UserProfile'),
        ),
    ]
