# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 18:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0011_auto_20170809_1425'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='fk_user_profile',
            new_name='fk_user',
        ),
    ]
