# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-12 04:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0017_auto_20170811_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cause', models.CharField(max_length=60)),
                ('point_status', models.IntegerField()),
                ('point_date', models.DateField(auto_now_add=True)),
                ('point_value', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.UserProfile')),
            ],
        ),
    ]
