# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-13 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0018_gamereport'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='badge',
            field=models.CharField(blank=True, default='Apprentice', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='badge',
            unique_together=set([('max_points', 'min_points')]),
        ),
    ]
