# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0019_auto_20170813_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greenpoint',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/profile/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='images/btn-locale.png', null=True, upload_to='images/profile/'),
        ),
    ]
