# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0020_auto_20170814_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='images/btn-locale.png', upload_to='images/profile/'),
        ),
    ]
