# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0022_auto_20170815_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greenpoint',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/tree/'),
        ),
    ]
