# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0024_auto_20170815_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='images/logo.png', upload_to='images/profile/'),
        ),
    ]
