# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0025_auto_20170816_0329'),
    ]

    operations = [
        migrations.AddField(
            model_name='stats',
            name='reported_trees',
            field=models.IntegerField(default=0),
        ),
    ]
