# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0026_stats_reported_trees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stats',
            name='green_index',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='stats',
            name='population_density',
            field=models.FloatField(default=0),
        ),
    ]
