# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0027_auto_20170817_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='max_points',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='badge',
            name='min_points',
            field=models.IntegerField(unique=True),
        ),
    ]
